# Generated by Django 5.2.5 on 2026-02-21 14:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import robot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ozon', 'Озон'), ('wb', 'ВБ'), ('yandex', 'Яндекс Маркет'), ('cdek', 'СДЭК'), ('mail', 'Почта России +150₽')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'App пользователь',
                'verbose_name_plural': 'App пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес пункта выдачи')),
                ('marketplaces', models.ManyToManyField(blank=True, related_name='pickup_points', to='robot.marketplace', verbose_name='Маркетплейсы в этом ПВЗ')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('amount', models.CharField(default='0', max_length=128, verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('barcode_image', models.ImageField(upload_to=robot.models.barcode_upload_to, verbose_name='Изображение штрих-кода')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает.'), ('completed', 'Собран и погружен на ближайшую доставку.'), ('barcode_expired', 'Штрих код устарел.'), ('not_arrived_goods', 'Ваши товары еще не в Анастасиевке.'), ('insufficient_funds', 'Недостаточно средств.'), ('card_not_linked', 'Банковская карта не привязана.'), ('contact_manager', 'Свяжитесь с менеджером.'), ('processed', 'Обработан.'), ('arrived', 'Готов к выдаче.')], default='pending', max_length=128, verbose_name='Статус')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robot.marketplace', verbose_name='Маркетплейс')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='robot.pickuppoint', verbose_name='Пункт выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=512, verbose_name='Имя')),
                ('nick_name', models.CharField(default='NoName', max_length=32, verbose_name='Ник')),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram User ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
                ('app_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL, verbose_name='Привязанный app пользователь')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
    ]
