# Generated by Django 5.2.5 on 2026-02-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
