# Generated by Django 5.2.5 on 2026-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ozon", "Озон"),
                            ("wb", "ВБ"),
                            ("yandex", "Яндекс Маркет"),
                            ("cdek", "СДЭК"),
                            ("mail", "Почта России +150₽"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Маркетплейс",
                "verbose_name_plural": "Маркетплейсы",
            },
        ),
        migrations.RemoveField(
            model_name="pickuppoint",
            name="marketplace",
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="marketplaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="pickup_points",
                to="robot.marketplace",
                verbose_name="Маркетплейсы в этом ПВЗ",
            ),
        ),
    ]
