# Generated by Django 5.2.5 on 2026-02-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0002_marketplace_remove_pickuppoint_marketplace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pickup_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="robot.pickuppoint",
                verbose_name="Пункт выдачи",
            ),
        ),
    ]
