# Generated by Django 5.1.1 on 2024-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_pickuppoint_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='marketplace',
            field=models.CharField(choices=[('ozon', 'Озон'), ('wb', 'ВБ'), ('yandex', 'Яндекс Маркет'), ('cdek', 'СДЭК')], max_length=50, verbose_name='Название маркетплейса'),
        ),
    ]
