# Generated by Django 5.2.5 on 2026-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0002_appuser_phone_number_alter_appuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
