# Generated by Django 5.1.1 on 2024-10-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_pickuppoint_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('barcode_expired', 'Штрих код устарел'), ('not_arrived', 'Ваши товары еще не в Анастасиевке')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
