# Generated by Django 5.2.5 on 2026-02-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0003_alter_order_pickup_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="marketplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="robot.marketplace",
                verbose_name="Маркетплейс",
            ),
        ),
    ]
