# Generated by Django 5.2.5 on 2026-02-21 09:26

import robot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_order_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode_image',
            field=models.ImageField(upload_to=robot.models.barcode_upload_to, verbose_name='Изображение штрих-кода'),
        ),
    ]
