# Generated by Django 5.1.2 on 2024-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickuppoint",
            name="marketplace",
            field=models.CharField(
                choices=[
                    ("ozon", "Озон"),
                    ("wb", "ВБ"),
                    ("yandex", "Яндекс Маркет"),
                    ("cdek", "СДЭК"),
                    ("Почта России +150₽", "mail"),
                ],
                max_length=50,
                verbose_name="Название маркетплейса",
            ),
        ),
    ]
