# Generated by Django 5.1.2 on 2024-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0007_order_ammount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ammount",
        ),
    ]
