# Generated by Django 5.1.2 on 2024-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0008_remove_order_ammount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.CharField(
                default="0", max_length=128, verbose_name="Сумма заказа"
            ),
        ),
    ]
