# Generated by Django 5.1.4 on 2024-12-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(default='NoName', max_length=512, verbose_name='Имя'),
        ),
    ]
