# Generated by Django 5.1.7 on 2025-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_alter_telegramuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает.'), ('completed', 'Собран и погружен.'), ('barcode_expired', 'Штрих код устарел.'), ('not_arrived_goods', 'Ваши товары еще не в Анастасиевке.'), ('insufficient_funds', 'Недостаточно средств.'), ('card_not_linked', 'Банковская карта не привязана.'), ('contact_manager', 'Свяжитесь с менеджером.')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
